routes/web.php
<?php
### Backend
use App\Http\Controllers\Backend\BranchCategoryController;
use App\Http\Controllers\Backend\BranchController;
use App\Http\Controllers\Backend\KTCsettingController;
### Frontend
use App\Http\Controllers\Frontend\CardpageController;
use App\Http\Controllers\Frontend\Unionpay\UnionpayController;
use App\Http\Controllers\Frontend\Visa\VisaController;

use App\Http\Controllers\Frontend\AppStatusController;
use App\Http\Controllers\Frontend\CreditcardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'oap/admin','middleware' => 'admin.user'], function () {

	Route::post('/check/check-dup-title/', ['uses' =>'Backend\\CheckduptitleController@checkDupTitle'])->name('check.check-dup-title');

	Route::post('/check/check-dup-slug/', ['uses' =>'Backend\\CheckduptitleController@checkDupSlug'])->name('check.check-dup-slug');

	Route::post('/check/check-dup-titlepage/', ['uses' =>'Backend\\CheckduptitleController@checkDupTitlePage'])->name('check.check-dup-titlepage');

	Route::any('/file-delete', ['uses' =>'Backend\\PageleaveformController@deleteLayout'])->name('file-delete');

	Route::any('/file-muti-delete', ['uses' =>'Backend\\PageleaveformController@deleteLayoutMulti'])->name('file-muti-delete');

	Route::post('/check/duplication/product-category/{field}', ['as' => 'check.duplicated.product-category', 'uses' => 'Backend\\ProductCategoryController@checkDuplicated']);
	Route::any('/product-categories/{category_id}/restore', ['as' => 'restore.product-category', 'uses' => 'Backend\\ProductCategoryController@restore']);

   ### RESTORE
	Route::put('leads/restore/{id}',['uses' =>'Backend\\LeavefromappController@restore'])->name('lead-restore');

	### FOR Branch Categories
	Route::get('/branch-categories/{category_id}/restore', [BranchCategoryController::class, 'restore'])->name('restore.branch-category');


	### FOR Leads
	Route::post('/leads/edit/time-filter', ['as' => 'edit.leads.time-filter', 'uses' => 'Backend\\LeavefromappController@changeDuplicateFilterDate']);
	Route::any('/leads/export', ['as' => 'export.leads', 'uses' => 'Backend\LeavefromappController@export']);
	Route::any('/leads/exportLID', ['as' => 'export.leads-lid', 'uses' => 'Backend\LeavefromappController@exportWithLID']);
	Route::get('/leads/next-id', function () {
	    return response(["id" => (new \App\Repositories\LeadRepo())->getNextUniqueID()]);
    });

	### FOR Product Sync

	Route::get('/dev/product/sync', ['as' => 'product.sync', 'uses' => 'Backend\\ProductSyncController@sync']);
	Route::get('/dev/date/{num}/{unit}', function($num, $unit){
	    $dt = new \Carbon\Carbon($num.' '.$unit.' ago');
	    return $dt->startOfDay();
    });

	### OPTION SALARY
    Route::post('check/duplication/opt-salaries', ['as' => 'check.opt-salaries.existed', 'uses' => 'Backend\\OptsalaryController@checkDuplicated']);

	### OPTION Convenien Time
    Route::post('check/duplication/opt-convenien-time', ['as' => 'check.opt-convenien-time.existed', 'uses' => 'Backend\\OptconvenienttimeController@checkDuplicated']);

	Route::get('opt-convenient-times/order', 'Backend\OptconvenienttimeController@order')->name('opt-convenient-times-order');
	Route::post('opt-convenient-times/order-list', 'Backend\OptconvenienttimeController@orderlist')->name('opt-convenient-times-order-list');

	### FOR All restore routes
	try {
    foreach (\TCG\Voyager\Models\DataType::all() as $dataType) {
		    $breadController = $dataType->controller
		    					? $dataType->controller
                                : 'Voyager\VoyagerBaseController';
        Route::any($dataType->slug.'/{id}/restore', $breadController.'@restore')->name('record.'.$dataType->slug.'.restore');
        Route::get($dataType->slug.'/trash', $breadController.'@index')->name('voyager.'.$dataType->slug.'.trash');
        Route::post($dataType->slug.'/check_existed', $breadController.'@checkExisted')->name('record.'.$dataType->slug.'.check-existed');
    }
	} catch (\InvalidArgumentException $e) {
        throw new \InvalidArgumentException("Custom routes hasn't been configured because: ".$e->getMessage(), 1);
    } catch (\Exception $e) {
        // do nothing, might just be because table not yet migrated.
    }

	### For KTC Settings
	Route::group(['as' => 'admin.'], function () {
		Route::resource('ktc-settings', 'Backend\KTCsettingController')->only(['index', 'update']);
		Route::group(['as' => 'profile.', 'prefix' => 'profile'], function() {
		    Route::get('edit', 'Backend\UserProfileController@editProfile')->name('edit');
		    Route::put('edit', 'Backend\UserProfileController@updateProfile')->name('update');
        });
	});

	Route::get('/report/view', 'Backend\ReportController@view');
	Route::get('/report/export', 'Backend\ReportController@export')->name('export.report');

    Route::any('/api/report', ['uses' => 'Backend\\ReportController@getDashboardReport'])->name('api.oap.dashboard_report');
});

//Route::post('/file-delete', ['uses' =>'Backend\\UploaderController@myupload']);


//Frontend Route
Route::get('/', function () {
	if (config('app.debug') == false) {
		return false;
	}else{
		return view('welcome');
	}
});

// Route::get('/oap/phpinfo', function () {
// 	echo "2";
// 	return utf8_encode(phpinfo());
// });

// //mockup for api data
// Route::group(['as' => 'mockup.','prefix' => 'mockup'], function () {
//     include_once(__DIR__.'/mockup.php');
// });

Route::resource('oap/lead-submit', 'Frontend\\CreditcardController')->except([
	'index', 'create', 'show', 'edit' , 'update', 'destroy'
]);

//unionpay
Route::any('apply/ktc-unionpay/{namepage}/thankyou', [UnionpayController::class, 'thankyou'])->name('unionpay-thankyou');
Route::get('apply/ktc-unionpay/{namepage}', [UnionpayController::class, 'index'])->where('namepage', '^((?!\w*thankyou\w*).)*$')->name('unionpay');
//Route::get('apply/ktc-unionpay/{namepage}', [UnionpayController::class, 'index'])->where('namepage', '\b(\w*thankyou\w*)\b')->name('unionpay2');
//visa
Route::any('offer/{product}/{namepage}/thankyou',[VisaController::class, 'thankyou'])->name('visa-thankyou');

Route::get('offer/{product}/{namepage}/',[VisaController::class, 'index'])->where('namepage', '^((?!\w*thankyou\w*).)*$')->name('visa');



Route::get('apply/global-menu', [CardpageController::class, 'pageGlobal'])->name('page-global');
Route::get('apply/{namepage}', ['uses' =>'Frontend\\CardpageController@page'])->name('page-index');


Route::get('apply/{namepage}/thankyou', [CreditcardController::class, 'leadSubmitResult'])->name('thankyou');
Route::get('apply/{namepage}/repetitive', [CreditcardController::class, 'leadSubmitResult'])->name('repetitive');



//app-check
Route::get('application-status', [AppStatusController::class, 'index'])->name('app-status.index');
Route::post('application-status', [AppStatusController::class, 'otpReq'])->name('app-status.otp-req');
Route::get('application-status/result', [AppStatusController::class, 'result'])->name('app-status.result');

//ALL Voyager route can  be overridden by Custom
Route::group(['prefix' => 'oap/admin'], function () {
	Voyager::routes();
});

app/Http/Controllers/Backend/ActivitiesLogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\ActivitiesLogApplyCard;
use App\ActivitiesLogAppStatus;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use DateTime;

class ActivitiesLogController extends Controller
{
    //

    public function getLog(Request $request)
    {
        $type1 = array('citizenID');
        $type2 = array('phoneNo', 'email');
        $check_filter = array('logDateBegin', 'logDateEnd', 'logTimeBegin', 'logTimeEnd', 'os', 'logTypeID');

        try {
            // check mandatory params
        if ($request->requestID == null || $request->pageNo == null || $request->itemPerPage == null) {
                return $this->responseSystemError($request->requestID);
        }

        $requestID = $request->requestID;
            if (gettype($request->itemPerPage) != "integer" || gettype($request->pageNo) != "integer") {
                return $this->responseSystemError($request->requestID);
            }
        $per_page = $request->itemPerPage;
        $request->page = $request->pageNo;
        if (!isset($request->logFilter)) {
            $app_status = ActivitiesLogAppStatus::all();
            $apply_card = ActivitiesLogAppStatus::all();

            foreach ($apply_card as $key => $value) {
                $merge_log = $app_status->push($value);
            }

            $sorted = $merge_log->sortByDesc('date_time');
            $paginator = new Paginator($sorted->values()->all(), $per_page, $request->page);

            $new_logs = array();
            foreach ($paginator->items() as $key => $value) {
                $new_logs[$key]['logID'] = $value->log_id;
                    if (mb_substr($value->log_id, 0, 1) == 'A') {
                        $type = 2;
                    } elseif (strrpos($value->log_id, 'B') != null) {
                    $type = 1;
                }
                $new_logs[$key]['logTypeID'] = $type;

                $newdate = new DateTime($value->date_time);

                    $new_logs[$key]['logDate'] = $newdate->format('YmdHms');

                $new_logs[$key]['os'] = $value->os;
                    $new_logs[$key]['browserIp'] = $value->browser;

                if ($type == 1) {
                    $new_logs[$key]['citizenID'] = $value->citizen_id;
                } else {
                    $new_logs[$key]['phoneNo'] = $value->phone_no;
                    $new_logs[$key]['email'] = $value->email;
                }

                    $value->cf1 = json_decode($value->cf1);
                    $value->cf2 = json_decode($value->cf2);
                    $value->custom_params = json_decode($value->custom_params);

                    //custom_params

                $new_logs[$key]['logDetail'] = $value;

            }
            $str = array(
                'requestID' => $request->requestID,
                'responseID' => $this->genResNo(),
                'responseCode' => '100',
                'responseMessage' => 'SUCCESS',
                'logs' => $new_logs, //$logs->items(), // get data from paginator
                'totalItem' => $paginator->count(),
            );

            return $str;

            } else {
                foreach ($request->logFilter as $key => $value) {
                    // check optional if params are in spec
                    if (!in_array($key, $check_filter) && !in_array($key, $type1) && !in_array($key, $type2)) {
                        return $this->responseSystemError($request->requestID);

        }
                }
            }

        $log_filter = $request->logFilter;

        if (isset($log_filter['logTypeID'])) {

            $type = $log_filter['logTypeID'];

            if (isset($log_filter['logDateBegin']) && isset($log_filter['logDateEnd'])) {
                $start = $log_filter['logDateBegin'];
                $end = $log_filter['logDateEnd'];
            } elseif (isset($log_filter['logDateEnd'])) {
                $end = $log_filter['logDateEnd'];
            } elseif (isset($log_filter['logDateBegin'])) {
                $start = $log_filter['logDateBegin'];
            }

                if (isset($log_filter['logTimeBegin']) && isset($log_filter['logTimeEnd'])) {
                    $time_start = $log_filter['logTimeBegin'];
                    $time_end = $log_filter['logTimeEnd'];
                } elseif (isset($log_filter['logTimeEnd'])) {
                    $time_end = $log_filter['logTimeEnd'];
                } elseif (isset($log_filter['logTimeBegin'])) {
                    $time_start = $log_filter['logTimeBegin'];
                }

            foreach ($log_filter as $key => $value) {
                if ($type == 1) {
                    if (in_array($key, $type2)) {
                            /*  $result = null;
                            break; */
                            return $this->responseNoData($request->requestID);

                    }
                } elseif ($type == 2) {
                    if (in_array($key, $type1)) {
/*                             $result = null;
break; */
                            return $this->responseNoData($request->requestID);

                    }
                }
            }
        } elseif (!isset($log_filter['logTypeID'])) {

                if (isset($log_filter['logDateBegin']) && isset($log_filter['logDateEnd'])) {
                    $start = $log_filter['logDateBegin'];
                    $end = $log_filter['logDateEnd'];
                } elseif (isset($log_filter['logDateEnd'])) {
                    $end = $log_filter['logDateEnd'];
                } elseif (isset($log_filter['logDateBegin'])) {
                    $start = $log_filter['logDateBegin'];
                }

                if (isset($log_filter['logTimeBegin']) && isset($log_filter['logTimeEnd'])) {
                    $time_start = $log_filter['logTimeBegin'];
                    $time_end = $log_filter['logTimeEnd'];
                } elseif (isset($log_filter['logTimeEnd'])) {
                    $time_end = $log_filter['logTimeEnd'];
                } elseif (isset($log_filter['logTimeBegin'])) {
                    $time_start = $log_filter['logTimeBegin'];
                }

                $filter = $this->mapFilter($log_filter);
                $a1 = 0;
                $a2 = 0;

                foreach ($log_filter as $key => $value) {
                    if (in_array($key, $type1)) {
                        $a1++;
                    } elseif (in_array($key, $type2)) {
                        $a2++;
                    }
                }

                if ($a1 > 0 && $a2 > 0) { // type error
                    $merge_log = null;
                } elseif ($a1 > 0 && $a2 == 0) { // type ActivitiesLogAppStatus
                    //$merge_log = ActivitiesLogAppStatus::where($filter)->get();
                    /* TODO */

                    /*   if (isset($start) && isset($end)) {

                    $merge_log = ActivitiesLogAppStatus::whereDate('date_time', '>=', $start)
                    ->whereDate('date_time', '<=', $end)
                    ->where($filter)
                    ->paginate($per_page);
                    } elseif (isset($start)) {
                    $merge_log = ActivitiesLogAppStatus::whereDate('date_time', '>=', $start)
                    ->where($filter)
                    ->paginate($per_page);
                    } elseif (isset($end)) {
                    $merge_log = ActivitiesLogAppStatus::whereDate('date_time', '<=', $end)
                    ->where($filter)
                    ->paginate($per_page);
                    } else {
                    $merge_log = ActivitiesLogAppStatus::where($filter)
                    ->paginate($per_page);
                    } */

                    if (isset($start) && isset($end)) { //done

                        if (isset($time_start) && isset($time_end)) {
                            $time_start = new DateTime($time_start);
                            $time_end = new DateTime($time_end);

                            $new_time_start = $time_start->format('Hms');
                            $new_time_end = $time_end->format('Hms');

                            $merge_log = ActivitiesLogAppStatus::whereTime('date_time', '>=', \Carbon\Carbon::parse($new_time_start))
                                ->whereTime('date_time', '<=', \Carbon\Carbon::parse($new_time_end))
                                ->whereDate('date_time', '>=', $start)
                                ->whereDate('date_time', '<=', $end)
                                ->where($filter)
                                ->paginate($per_page);

                        } elseif (isset($time_start)) {

                            $time_start = new DateTime($time_start);

                            $new_time_start = $time_start->format('Hms');

                            $merge_log = ActivitiesLogAppStatus::whereTime('date_time', '>=', \Carbon\Carbon::parse($new_time_start))
                                ->whereDate('date_time', '>=', $start)
                                ->whereDate('date_time', '<=', $end)
                                ->where($filter)
                                ->paginate($per_page);

                        } elseif (isset($time_end)) {

                            $time_end = new DateTime($time_end);

                            $new_time_end = $time_end->format('Hms');

                            $merge_log = ActivitiesLogAppStatus::whereTime('date_time', '<=', \Carbon\Carbon::parse($new_time_end))
                                ->whereDate('date_time', '>=', $start)
                                ->whereDate('date_time', '<=', $end)
                                ->where($filter)
                                ->paginate($per_page);

                        } else {
                            $merge_log = ActivitiesLogAppStatus::where($filter)

resources/views/backend/branch-browse.blade.php
@extends('voyager::master')

@section('page_title', __('voyager::generic.viewing').' '.$dataType->display_name_plural)

@section('page_header')
<div class="container-fluid">
    <h1 class="page-title">
        @if($browse_state=="trash")
        <i class="voyager-trash"></i>
        {{ 'Trashed ' }}
        @else
        <i class="{{ $dataType->icon }}"></i>
        @endif{{ $dataType->display_name_plural }}
    </h1>
    @if($browse_state!=="trash")
    @can('add', app($dataType->model_name))
    <a href="{{ route('voyager.'.$dataType->slug.'.create') }}" class="btn btn-success btn-add-new">
        <i class="voyager-plus"></i> <span>{{ __('voyager::generic.add_new') }}</span>
    </a>
    @endcan
    @endif
    @can('delete', app($dataType->model_name))
    @if($browse_state!=="trash")
      @include('voyager::partials.bulk-delete')
    @else
      @include('backend.partials.bulk-restore')
    @endif
    @endcan
    @can('edit', app($dataType->model_name))
    @if(isset($dataType->order_column) && isset($dataType->order_display_column))
    <a href="{{ route('voyager.'.$dataType->slug.'.order') }}" class="btn btn-primary">
        <i class="voyager-list"></i> <span>{{ __('voyager::bread.order') }}</span>
    </a>
    @endif
    @endcan
    @include('voyager::multilingual.language-selector')
</div>
@stop

@section('content')
<div class="page-content">
    @include('voyager::alerts')
    {{-- @include('voyager::dimmers') --}}
    <div class="page-content browse container-fluid">
        <div class="alerts">
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="brows-state">
                    <span class="badge badge-info">{{ $count_state->all }}</span> items, <a href="{{ route('voyager.'.$dataType->slug.'.index') }}">active ({{ $count_state->all-$count_state->trashed }})</a> | <a href="{{ route('voyager.'.$dataType->slug.'.trash') }}">trash ({{ $count_state->trashed }})</a>
                </div>
                <div class="panel panel-bordered">
                    <div class="panel-body">
                        <table id="dataTable" class="table table-hover">
                            <thead>
                                <tr>
                                    @can('delete',app($dataType->model_name))
                                    <th width="5%">
                                        <input type="checkbox" class="select_all">
                                    </th>
                                    @endcan
                                    <th width="20%">
                                        Title
                                    </th>
                                    <th width="10%">
                                        Code
                                    </th>
                                    <th width="25%">
                                        Description
                                    </th>
                                    <th width="13%">
                                        Updated
                                    </th>
                                    @if($browse_state=="trash")
                                    <!-- <th width="10%">
                                        Deleted
                                    </th> -->
                                    @endif

                                    <th class="actions text-right" width="20%">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($branches as $item => $form)
                                <tr>
                                    @can('delete',app($dataType->model_name))
                                    <td>
                                        <input type="checkbox" name="row_id" id="checkbox_{{ $form->id }} ?>" value="{{ $form->id }}">
                                    </td>
                                    @endcan
                                    <td>
                                        {{ $form->title }}
                                    </td>
                                    <td>
                                        {{ $form->code }}
                                    </td>
                                    <td class="no-sort no-click">
                                        {{ $form->description }}
                                    </td>
                                    <td>
                                        <input type="hidden" value="{{ $form->updated_at }}">
                                        {{ formatDateTimeThat($form->updated_at) }}
                                    </td>

                                    @if($browse_state=="trash")
                                    <!-- <td class="text-center">
                                        @if($form->trashed())
                                        <span class="badge badge-pill badge-danger">DELETED</span>
                                        <a href="{{ route('restore.product-category', $form->id) }}" type="button" class="btn btn-link">Restore</a>
                                        @endif
                                    </td> -->
                                    @endif

                                    <td class="no-sort no-click bread-actions">

                                        @if($browse_state!=="trash")
                                        @can('delete',app($dataType->model_name))
                                        @if($browse_state!=="trash")
                                        <div class="btn btn-sm btn-danger pull-right delete" data-id="{{ $form->id }}" data-action="{{ route('voyager.'.$dataType->slug.'.destroy', $form->id) }}">
                                            <i class="voyager-trash"></i> {{ __('voyager::generic.delete') }}
                                        </div>
                                        @endif
                                        @endcan
                                        @can('edit',app($dataType->model_name))
                                        <a href="{{ URL('/oap/admin/'.$dataType->slug.'/'.$form->id.'/edit ') }}" title="Edit" class="btn btn-sm btn-primary pull-right edit">
                                            <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">Edit</span>
                                        </a>
                                        @endcan
                                        @else
                                        <div class="btn btn-sm btn-restore pull-right restore" data-id="{{ $form->id }}">
                                            <i class="voyager-refresh"></i> {{ __('Restore') }}
                                        </div>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal modal-danger fade" tabindex="-1" id="delete_modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <i class="voyager-trash"></i> {{ __('voyager::generic.delete_question') }} {{ $dataType->display_name_singular }}?
                    </h4>
                </div>
                <div class="modal-footer">
                    <form action="#" id="delete_form" method="POST">
                        {{ method_field("DELETE") }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger pull-right delete-confirm" value="{{ __('voyager::generic.delete_this_confirm') }} {{ $dataType->display_name_singular }}">
                    </form>
                    <button type="button" class="btn btn-default pull-right" data-dismiss="modal">{{ __('voyager::generic.cancel') }}</button>
                </div>
            </div>
        </div>
    </div>
    {{-- Restore modal--}}
    <div class="modal modal-info fade" tabindex="-1" id="restore_modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <i class="voyager-refresh"></i> {{ 'Are you sure you want to restore this' }} {{ $dataType->display_name_singular }}?
                    </h4>
                </div>
                <div class="modal-footer">
                    <form action="#" id="restore_form" method="POST">
                        {{ method_field("PUT") }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-success pull-right restore-confirm" value="Yes, restore this item">
                    </form>
                    <button type="button" class="btn btn-default pull-right" data-dismiss="modal">{{ __('voyager::generic.cancel') }}</button>
                </div>
            </div>
        </div>
    </div>
</div>
@stop
<?php $__env->startSection('javascript'); ?>
<script>
    jQuery( document ).ready(function() {
        $('#dataTable').DataTable({
            "order": [[4,"desc"]],
            "columnDefs": [
            {"targets": 0, "searchable":  false, "orderable": false},
            {"targets": 5, "searchable":  false, "orderable": false},
            {"targets": 4, "type": "numeric-comma" }
            ],
            responsive: true
        });
        $('.select_all').on('click', function(e) {
            $('input[name="row_id"]').prop('checked', $(this).prop('checked'));
        });
        $('td').on('click', '.delete', function (e) {
            $('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.destroy', ['menu' => '__menu']) }}'.replace('__menu', $(this).data('id'));
            $('#delete_modal').modal('show');
        });
        $('td').on('click', '.restore', function (e) {
          $('#restore_form')[0].action = '{{ route("record.$dataType->slug.restore", ['menu' => '__menu']) }}'.replace('__menu', $(this).data('id'));

          $('#restore_modal').modal('show');

        });
    });
</script>
<?php $__env->stopSection(); ?>

resources/views/backend/profile.blade.php
@extends('voyager::master')

@section('css')
    <style>
        .user-email {
            font-size: .85rem;
            margin-bottom: 1.5em;
        }
    </style>
@stop

@section('content')
    <div style="background-size:cover; background-image: url({{ Voyager::image( Voyager::setting('admin.bg_image'), config('voyager.assets_path') . '/images/bg.jpg') }}); background-position: center center;position:absolute; top:0; left:0; width:100%; height:300px;"></div>
    <div style="height:160px; display:block; width:100%"></div>
    <div style="position:relative; z-index:9; text-align:center;">
        <img src="@if( !filter_var(Auth::user()->avatar, FILTER_VALIDATE_URL)){{ Voyager::image( Auth::user()->avatar ) }}@else{{ Auth::user()->avatar }}@endif"
             class="avatar"
             style="border-radius:50%; width:150px; height:150px; border:5px solid #fff;"
             alt="{{ Auth::user()->name }} avatar">
        <h4>{{ ucwords(Auth::user()->name) }}</h4>
        <div class="user-email text-muted">{{ ucwords(Auth::user()->email) }}</div>
        <p>{{ Auth::user()->bio }}</p>
        <a href="{{ route('admin.profile.edit') }}" class="btn btn-primary">{{ __('voyager::profile.edit') }}</a>
    </div>
@stop